name: hive_book_list_sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.0-24.0.dev <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  uuid: ^3.0.6
  flutter_slidable: ^1.2.0
  image_picker: ^0.8.5+3
  pedantic_mono: ^1.19.2
  local_auth: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10

flutter:
  uses-material-design: true
